### ISSUE TITLE
Appcheck Package is not correctly using the provider Device Check vs AppAttest For iOS 14+ devices

### ISSUE THREAD

**Issue by SureshKumarToverto** [robingenz/capacitor-firebase-authentication-demo#227] opened 2024-01-20 13:34 UTC
**Describe the bug**
When we test it on IOS 14+ devices it' still uses the Device check instead of AppAttest.

**To Reproduce**
[github.com/TamilselvanMariyappan/capacitor-firebase-authentication-demo/tree/AppAttest-AppCheck](https://github.com/TamilselvanMariyappan/capacitor-firebase-authentication-demo/tree/AppAttest-AppCheck)

**Steps to reproduce**
By logging the device
Get bearer token response, inspect with JWT response you can see the response

**Expected behavior**
{
"sub": "1:06:ios:1b3f479e7***",
"aud": [
"projects/85*********",
"projects/ABC"
],
"provider": "device_check_app_attest",
"iss": "https://firebaseappcheck.googleapis.com/",
"exp": 1695293981,
"iat": 1695290381,
"jti": "EBdv4gM8*************i1j1lMX"
}`

**Current behavior**
{ "sub": "1:06:ios:3b262cd82",
"aud": [
"projects/85*******",
"projects/ABC"
],
"provider": "device_check_device_identification",
"iss": "https://firebaseappcheck.googleapis.com/",
"exp": 1695284564,
"iat": 1695280964,
"jti": "G6vqvRPv**********60tRmR1"
}
**Current behavior - Screenshots**
![Screenshot 2024-01-20 at 7 05 50 PM](https://github.com/robingenz/capacitor-firebase-authentication-demo/assets/155732803/be08b49e-b9aa-4dfa-976d-5c570bc2e720)

**Smartphone (please complete the following information):**

**- Device: [iPhone6]**
- OS: iOS 15.8

**Comment by robingenz** [comment] 2024-01-20 13:57
I close this as duplicate of https://github.com/capawesome-team/capacitor-firebase/issues/490

**Closed** 2024-01-20 13:57 UTC
